const { OpenAI } = require('openai');

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

const generateQuestions = async (surveyName, surveyDescription, allQuestions, keyword) => {
  try {


    console.log(`Generating question based on this keyword: + ${keyword})`);

    const prompt = `Create one human-verification question for the topic "${keyword || 'General Bot Detection'}". 
      The question should be open-ended, personal, and designed to reveal genuine human thought.
      Return ONLY the question text, nothing else.`;

    const response = await client.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "user", content: prompt }
      ],
      max_tokens: 200
    });

    // Extract the question text directly
    const question = response.choices[0].message.content.trim();

    console.log('response',response);
    console.log('fetched question',question);
    return question;
  }
  catch (error) {
    console.error("error in generating questions:", error);
    throw error;
  }
};



const verifyGenuineResponse = async (questionText, userAnswer) => {
    try {
        const prompt = `
        You are a highly strictly spam-detection filter for a survey system. 
        A user was asked this specific question: "${questionText}"
        The user responded with: "${userAnswer}"

        Your job is to detect if this response is generated by a bot or spammer. 
        Flag it as a bot if the answer is:
        1. complete gibberish (e.g., "asdfgasdfg").
        2. blatantly copy-pasted nonsense or completely unrelated to the topic.
        3. overtly robotic
        
        Respond strictly in valid JSON format:
        {
          "isBot": true
        }
        `;

        const response = await client.chat.completions.create({
            model: "gpt-4o",
            messages: [{ role: "user", content: prompt }],
            temperature: 0.1,
            max_tokens: 300
        });

        const replyString = response.choices[0].message.content.trim();
        const parsedReply = JSON.parse(replyString);
        return { isBot: parsedReply.isBot };
        
    } catch (error) {
        console.error("Error in AI Bot Verification:", error);
        return { isBot: false };
    }
};

module.exports = { generateQuestions, verifyGenuineResponse };
